### ISSUE TITLE
First Feature Block Underneath Banner

### ISSUE THREAD

**Issue by jhreis** [themefisher/educenter-hugo#11]
The live [demo](http://demo.themefisher.com/educenter-hugo/) on GitHub, has the first section header sliding under the main image. This is actually different than the [demo on the Hugo site](https://themes.gohugo.io/theme/educenter-hugo/).

It appears that d82a39f is the culprit, as checking out the commit before this has the correct behavior. 

Screenshot:
![Image of the broken section behavior](https://user-images.githubusercontent.com/2781690/80819201-888b1300-8ba2-11ea-9db5-057cff88860b.png)

**Comment by Somrat37** [comment]
Hey there, thanks for your concern, I fixed this issue, please download the latest code.
