### ISSUE TITLE
Broken link to documentation 

### ISSUE THREAD

**Issue by Tomodachi2019** [themefisher/educenter-hugo#12]
I am fond of your theme "educenter" but I am not interested in using neither netlify nor forestry. So I wanted to learn how I have to configurate Hugo to get it running. However, the link [https://documentation.themefisher.com/docs/educenter-hugo/](url) is broken and within the documentation directory [https://documentation.themefisher.com/](url) the theme is unknown.

**Comment by Somrat37** [comment]
hey there, actually there is no documentation on this theme, so please follow this original documentation on Hugo https://gohugo.io/getting-started/quick-start/

and if you need any particular help then ask me, I will always be here.

**Comment by Somrat37** [comment]
I am going to close this issue, if you face any problem, create a new issue.
