### ISSUE TITLE
Cannot access educenter hugo documentation to change theme color

### ISSUE THREAD

**Issue by cloudmiracle** [themefisher/educenter-hugo#15]
I cannot access this link https://documentation.themefisher.com/docs/educenter-hugo/ 

Please help to bring it up and how to change theme color.

Regards,
Viet

**Comment by developer-evan** [comment]
Hey there, we are creating a new guide for Hugo themes, please visit https://docs.gethugothemes.com/guide/#colors-and-fonts this site to customize your theme. 

also if you like our theme, a star to the repository would be amazing, thanks.
