### ISSUE TITLE
Custom Scss

### ISSUE THREAD

**Issue by spiropoulos94** [themefisher/educenter-hugo#19]
i would like to know that to do in order to add a new custom scss file which overwrites all the previous ones, in order to apply my custom styles

**Comment by developer-evan** [comment]
hey there, create a new file `custom.scss` in `scss` folder. Then add it on style.scss (i.e `@import 'custom.scss';`) at the bottom line.

**Comment by developer-evan** [comment]
hey there, create a new file `custom.scss` in `scss` folder. Then add it on style.scss (i.e `@import 'custom.scss';`) at the bottom line.

**Comment by spiropoulos94** [comment]
thank you very much for your response!
