### ISSUE TITLE
Proposal : Improve SEO with <link rel="alternate">

### ISSUE THREAD

**Issue by sachaarbonel** [themefisher/educenter-hugo#20]
Hi themefisher team, thank's for this great theme! It seems to me that is a [good SEO practice](https://support.google.com/webmasters/answer/189077). Also ghost [have a section](https://ghost.org/tutorials/multi-language-content/) on this

**Comment by developer-evan** [comment]
Hey @sachaarbonel 

Thanks for your concern. I didn't get it properly what you said, can you please explain in details so we can improve our theme. Or it will be great if you make a pull request.

**Comment by sachaarbonel** [comment]
I did something like this in `layouts/partials/head.html` 👍 

```html
{{ "<!-- multilingual SEO optimizations -->" | safeHTML }}
  {{ if .IsTranslated }}
      {{ range .Translations }}
          <link rel="alternate" hreflang="{{ .Lang }}" href="https://gallant-kirch-993286.netlify.app{{ .Permalink }}">
      {{ end }}

  {{ end }}
```
Sorry for the ugly hardcoded url but still new to gohugo and I tried everything but my baseUrl doesn't seem to work.

**Comment by developer-evan** [comment]
@sachaarbonel 

I am implementing this code. Thanks for being with themefisher.
