### ISSUE TITLE
Main menu entries disappear when name is changed

### ISSUE THREAD

**Issue by imeshl** [themefisher/educenter-hugo#22]
Steps to reproduce:

1. Install theme following instructions in documentation
2. Change names of any main menu entry eg:

```
[[menu.main]]
name = "About"
URL = "about"
weight = 1
```

to 

```
[[menu.main]]
name = "Mission"
URL = "about"
weight = 1 
```
3. Build with hugo server & the menu entry gets hidden.

**Comment by developer-evan** [comment]
Hello @imeshl 

This is happening because of multilingual translations. This issue has been fixed now, You can download the latest code and use it.
