### ISSUE TITLE
LaTeX code

### ISSUE THREAD

**Issue by Jorge-hercas** [themefisher/educenter-hugo#25]
Hi, I've been trying to write latex code for equations in this template but it doesn't recognize me, is there any way to fix this?

**Comment by somratpro** [comment]
Hello @Jorge-hercas 

Thanks for using our template, you can read this [article](https://geoffruddock.com/math-typesetting-in-hugo/) to implement LaTex, Or you can contact our CEO for paid support at mehedi@themefisher.com.
