### ISSUE TITLE
Theme doesn't load with JS disabled

### ISSUE THREAD

**Issue by aschrijver** [themefisher/educenter-hugo#26]
Your theme is absolutely delicious. However, for those having JS disabled the page only shows the loader icon and never passes that. It'd be great if with JS disabled the site downgrades and all site content were still accessible (with exception of dynamic effects).

**Comment by somratpro** [comment]
Hello @aschrijver 

First you need to disable the site preloader from `config.toml` by making `preloader = false`. then you can load the site without js.

**Comment by aschrijver** [comment]
Thanks for the help @somratpro and for Hugo.. a fantastic project!
