### ISSUE TITLE
How to use this them on Github page?

### ISSUE THREAD

**Issue by namkyodai** [themefisher/educenter-hugo#31]
Hi,
I am trying to use this them for github page.
I use either
Hugo
hugo -t <theme name>

To generate public folder.

the github page appears but all preloaders disappear, the page looks like it cannot load components from the thems.

appreciate if you can advise on how to solve this.

thanks

Nam

**Comment by somratpro** [comment]
Hello @namkyodai 

please provide the exact base URL in your theme config.toml file before generating the public folder. then it will load correctly....

**Comment by namkyodai** [comment]
Hi @somratpro, really appreciate your advice on this. It works after I followed your instruction.
