### ISSUE TITLE
logo is stretched 

### ISSUE THREAD

**Issue by Kwaskoff** [themefisher/educenter-hugo#34]
Hi,guys 
in this demo https://demo.themefisher.com/educenter/
you can see logo
![image](https://user-images.githubusercontent.com/15308024/126031084-c61b5953-d87f-492d-bcaf-d936a3302a07.png)
it looks smooth, like image is stretched
original file https://demo.themefisher.com/educenter/images/logo.png
html code https://docs.themefisher.com/educenter/change-logo/

**Comment by tfsomrat** [comment]
Hello @Kwaskoff 

I didn't get your issue, please explain what do you want to do
