### ISSUE TITLE
Deploy failed

### ISSUE THREAD

**Issue by uelig** [themefisher/educenter-hugo#4]
Hi
I went trough the installing three times (text and video), but the deploy fails.
I deleted after a fail "all" from github-forestry-netifli.

When I go trough the build log then I see:
9:54:18 PM: Installing Hugo 0.60.1
-> 0.60.1 is an older version as shown in the forestry dialog.

any hint?
Best Ueli

**Comment by themefisherDev** [comment]
hey, 
I don't know what's going wrong with you, i just added this template in forestry without any problem. did you follow this on click forestry import procedure?

**Comment by uelig** [comment]
Hi,
I tried another setup-round, same result.
I tried:
- following the video (yesterday)
- using the button "import to forestry" (today)

So I have:
- a git fork of the template
- imported it in forestry
- set the baseurl to "https://letsgroove.netlify.com"
- setup netifly
- changed the sitename to "letsgroove"
- "depolyed" and "re-deployed with cleaning the cache"

Result: "Site deploy failed" with an error "255"
I see:
"9:11:44 AM: Installing Hugo 0.60.1" it's not the latest
I see an Error:
"9:11:46 AM: Error: add site dependencies: load resources: loading translations: "/opt/build/repo/exampleSite/i18n/en.yaml:1:1": failed to load translations: unable to parse translation #37 because missing "id" key"
Then to the end:
"9:11:48 AM: Error running command: Build script returned non-zero exit code: 255
9:11:48 AM: Failing build: Failed to build site
9:11:49 AM: failed during stage 'building site': Build script returned non-zero exit code: 255"

Best Ueli

**Comment by themefisherDev** [comment]
So you see this error on netlify, right?

**Comment by uelig** [comment]
I found the origin of the deploy error.
In "/repo/exampleSite/i18n/en.yaml" was at the end an "id" without key. I checked it with the fr version and then deleted this "id without key". The last entry in the translation is "download".

Now, the depoly is fine. In addition, I modified the netifly config file, using now the newest hogo build, same as shown in forestry.

All is fine now, thanks
Ueli
