### ISSUE TITLE
How can I customize css ?

### ISSUE THREAD

**Issue by MarieMarieL** [themefisher/educenter-hugo#5]
I have tried to edit the SCSS file in the asset folder of my project, but when I rerun hugo server my changes are set back to the original. I thought we were just supposed to edit the file on the asset folder (and not directly from the theme).

Can anybody tell me where I'm going wrong?
Are we at least able to edit the CSS of this theme?

Thank you very much

**Comment by rootsongjc** [comment]
@MarieMarieL You can edit the configs in `assets/scss` folder.

**Comment by MarieMarieL** [comment]
Thank you for your answer.
The problem is that when I edit this file (the one with the blue icon before), the changes I made are deleted when I launch Hugo server.
![Code_Q4FLKbq3D8](https://user-images.githubusercontent.com/33684221/74013945-e0442480-498d-11ea-88e2-c12782389339.png)

In my `head.html` `partial `folder, the stylesheet is referred with `{{ $styles.Permalink }}`, does this mean that the theme will find by itself the SCSS file (in the `assets `folder)?

```
{{ "<!-- Main Stylesheet -->" | safeHTML }}
    {{ $styles := resources.Get "scss/style.scss" | toCSS }}
    <link rel="stylesheet" href="{{ $styles.Permalink }}" media="screen">
```

**Comment by rootsongjc** [comment]
@MarieMarieL You should edit these files.
```
_buttons.scss
_common.scss
_mixins.scss
_typography.scss
_variables.scss
style.scss
templates/_homepage.scss
templates/_navigation.scss
templates/_otherspage.scss
templates/_slider.scss
```
`resources` folder is temprory  and built with hugo.

My own website is using this theme https://jimmysong.io , so I am very familiar with this theme.

**Comment by MarieMarieL** [comment]
Ok I see, thank you very much !
I don't have such files for the moment in my project, that's why I didn't understand.

And do you reffer these files in the head.html partial folder ? Simply like this ?

**Comment by rootsongjc** [comment]
No. No need to refer to these files. Just keep the file as its original state.
