### ISSUE TITLE
Insecure mixed content detected

### ISSUE THREAD

**Issue by sradams88** [themefisher/educenter-hugo#8]
I go thru the steps for the website, but when I deploy on netlify it seems only the html is loading without the css. I look at the deploy details and it warns of insecure mixed content being detected. I don't know too much about this stuff. So, any help would be much appreciated.

![image](https://user-images.githubusercontent.com/47198841/77455851-65618c80-6dc8-11ea-9334-8ebeb2445bd9.png)

**Comment by Somrat37** [comment]
You must don't match the baseURL. Please make sure that the baseurl you entered in forestry and netlify are the same.
