### ISSUE TITLE
Following documentation but result looks bad

### ISSUE THREAD

**Issue by arnaudbore** [themefisher/educenter-hugo#9]
Hi,

I followed the documentation but at the end it looks like the theme is not used. 
[see here](https://5e7e6dd9bbc752f3ebce2e44--lucid-shockley-00501b.netlify.com/)

Thank you in advance for your help.

**Comment by mehedi-sharif** [comment]
Please add the base url in config file

Mehedi Sharif
Themefisher
Themefisher@gmail.com
www.themefisher.com

**Comment by arnaudbore** [comment]
Great thank you ! It worked, maybe you should emphasize more on the importance of this step in the doc.

Arnaud
